name: Release

on:
  workflow_dispatch:
  push:
    branches: [main, dev]

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle (with cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew clean :patches:buildAndroid

      - name: List Build Artifacts
        run: ls -la patches/build/libs/

      - name: Create Git tag
        run: |
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          prerelease: ${{ github.ref == 'refs/heads/dev' }}
          body: |
            Automatically generated release for commit ${{ github.sha }}.
            Patches built from branch ${{ github.ref_name }}.
          files: |
            patches/build/libs/patches-*.rvp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ vars.GPG_FINGERPRINT }}

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: patches/build/libs/patches-*.rvp
